// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYVjfbNibVNJsZ87Q5rYOCXYuSndxsLhc',
    appId: '1:660420985633:web:36dd7d48001b74934fb460',
    messagingSenderId: '660420985633',
    projectId: 'mashrou3i-2bec0',
    authDomain: 'mashrou3i-2bec0.firebaseapp.com',
    storageBucket: 'mashrou3i-2bec0.firebasestorage.app',
    measurementId: 'G-JMCXEMBM2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUHcsJ1OsXFCl9Q5WrtHLLUVlUCdH2VFI',
    appId: '1:660420985633:android:367dbb8d182c29e44fb460',
    messagingSenderId: '660420985633',
    projectId: 'mashrou3i-2bec0',
    storageBucket: 'mashrou3i-2bec0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCayK8zV-J_zxqiYN87x9n4yAMwdLUnj-Y',
    appId: '1:660420985633:ios:9761de26e7232fb14fb460',
    messagingSenderId: '660420985633',
    projectId: 'mashrou3i-2bec0',
    storageBucket: 'mashrou3i-2bec0.firebasestorage.app',
    androidClientId: '660420985633-n4autab3rv6nuk3tvv6ov3nhmvrcpe3v.apps.googleusercontent.com',
    iosClientId: '660420985633-6iu755tf0tqgqqahi089jd9hre0qtfu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mashrou3iApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYVjfbNibVNJsZ87Q5rYOCXYuSndxsLhc',
    appId: '1:660420985633:web:4ae38b36236dd1864fb460',
    messagingSenderId: '660420985633',
    projectId: 'mashrou3i-2bec0',
    authDomain: 'mashrou3i-2bec0.firebaseapp.com',
    storageBucket: 'mashrou3i-2bec0.firebasestorage.app',
    measurementId: 'G-T6FF87R4ZT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCayK8zV-J_zxqiYN87x9n4yAMwdLUnj-Y',
    appId: '1:660420985633:ios:eb351c4de7006c394fb460',
    messagingSenderId: '660420985633',
    projectId: 'mashrou3i-2bec0',
    storageBucket: 'mashrou3i-2bec0.firebasestorage.app',
    androidClientId: '660420985633-n4autab3rv6nuk3tvv6ov3nhmvrcpe3v.apps.googleusercontent.com',
    iosClientId: '660420985633-reuo3hlvr5vjf7dikluc23eevgoltt4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mashrou3i',
  );

}